<!DOCTYPE html>

<html>
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        
        <link href="/templates/css/style.css" type="text/css" rel="stylesheet"/>
    </head>
    <body>
        <?= $content ?>
        
        <script src="/templates/js/script.js"></script>
    </body>
</html>